services:

  timescaledb:
    image: timescale/timescaledb-ha:pg17
    command: -c 'max_connections=500'
    container_name: timescale-gnoland
    restart: always
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: gnoland
    volumes:
      - spectra-data:/home/postgres/pgdata/data
    networks:
      - spectra
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d gnoland"]
      interval: 10s
      timeout: 5s
      retries: 5
    
  indexer:
    build:
      context: .
      args:
        GIT_COMMIT: dev
        GIT_TAG: dev
        GIT_BRANCH: dev
        VERSION: dev
      dockerfile: Dockerfile
    container_name: indexer
    restart: always
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: gnoland
    networks:
      - spectra
    depends_on:
      - timescaledb
    volumes:
      - ./config.yml:/app/config.yml:ro,Z
    command: ["run", "live", "--config", "/app/config.yml"]
  api:
    build:
      context: .
      args:
        GIT_COMMIT: dev
        GIT_TAG: dev
        GIT_BRANCH: dev
        VERSION: dev
      dockerfile: Dockerfile-api
    container_name: api
    restart: always
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      DB_HOST: timescaledb
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: 12345678
      DB_NAME: gnoland
    networks:
      - spectra
    depends_on:
      - timescaledb
    volumes:
      - ./config-api.yml:/app/config-api.yml:ro,Z
    command: ["-c", "/app/config-api.yml"]

networks:
  spectra:
    driver: bridge

volumes:
  spectra-data:
    driver: local
