// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: events.proto

package events_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TxEvents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TxEvents) Reset() {
	*x = TxEvents{}
	mi := &file_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TxEvents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxEvents) ProtoMessage() {}

func (x *TxEvents) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxEvents.ProtoReflect.Descriptor instead.
func (*TxEvents) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{0}
}

func (x *TxEvents) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AtType        string                 `protobuf:"bytes,1,opt,name=at_type,json=atType,proto3" json:"at_type,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Attributes    []*Attribute           `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	PkgPath       *string                `protobuf:"bytes,4,opt,name=pkg_path,json=pkgPath,proto3,oneof" json:"pkg_path,omitempty"` // Can be null or string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{1}
}

func (x *Event) GetAtType() string {
	if x != nil {
		return x.AtType
	}
	return ""
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetAttributes() []*Attribute {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Event) GetPkgPath() string {
	if x != nil && x.PkgPath != nil {
		return *x.PkgPath
	}
	return ""
}

type Attribute struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Key   string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*Attribute_StringValue
	//	*Attribute_Int64Value
	//	*Attribute_BoolValue
	//	*Attribute_DoubleValue
	Value         isAttribute_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Attribute) Reset() {
	*x = Attribute{}
	mi := &file_events_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Attribute) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attribute) ProtoMessage() {}

func (x *Attribute) ProtoReflect() protoreflect.Message {
	mi := &file_events_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attribute.ProtoReflect.Descriptor instead.
func (*Attribute) Descriptor() ([]byte, []int) {
	return file_events_proto_rawDescGZIP(), []int{2}
}

func (x *Attribute) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Attribute) GetValue() isAttribute_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Attribute) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Attribute_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Attribute) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Value.(*Attribute_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Attribute) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Attribute_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Attribute) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*Attribute_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

type isAttribute_Value interface {
	isAttribute_Value()
}

type Attribute_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Attribute_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Attribute_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Attribute_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,5,opt,name=double_value,json=doubleValue,proto3,oneof"` // leave this as double for now
}

func (*Attribute_StringValue) isAttribute_Value() {}

func (*Attribute_Int64Value) isAttribute_Value() {}

func (*Attribute_BoolValue) isAttribute_Value() {}

func (*Attribute_DoubleValue) isAttribute_Value() {}

var File_events_proto protoreflect.FileDescriptor

const file_events_proto_rawDesc = "" +
	"\n" +
	"\fevents.proto\x12\veventsproto\"6\n" +
	"\bTxEvents\x12*\n" +
	"\x06events\x18\x01 \x03(\v2\x12.eventsproto.EventR\x06events\"\x99\x01\n" +
	"\x05Event\x12\x17\n" +
	"\aat_type\x18\x01 \x01(\tR\x06atType\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x126\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2\x16.eventsproto.AttributeR\n" +
	"attributes\x12\x1e\n" +
	"\bpkg_path\x18\x04 \x01(\tH\x00R\apkgPath\x88\x01\x01B\v\n" +
	"\t_pkg_path\"\xb4\x01\n" +
	"\tAttribute\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12#\n" +
	"\fstring_value\x18\x02 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fdouble_value\x18\x05 \x01(\x01H\x00R\vdoubleValueB\a\n" +
	"\x05valueB\x19Z\x17../indexer/events_protob\x06proto3"

var (
	file_events_proto_rawDescOnce sync.Once
	file_events_proto_rawDescData []byte
)

func file_events_proto_rawDescGZIP() []byte {
	file_events_proto_rawDescOnce.Do(func() {
		file_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)))
	})
	return file_events_proto_rawDescData
}

var file_events_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_events_proto_goTypes = []any{
	(*TxEvents)(nil),  // 0: eventsproto.TxEvents
	(*Event)(nil),     // 1: eventsproto.Event
	(*Attribute)(nil), // 2: eventsproto.Attribute
}
var file_events_proto_depIdxs = []int32{
	1, // 0: eventsproto.TxEvents.events:type_name -> eventsproto.Event
	2, // 1: eventsproto.Event.attributes:type_name -> eventsproto.Attribute
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_events_proto_init() }
func file_events_proto_init() {
	if File_events_proto != nil {
		return
	}
	file_events_proto_msgTypes[1].OneofWrappers = []any{}
	file_events_proto_msgTypes[2].OneofWrappers = []any{
		(*Attribute_StringValue)(nil),
		(*Attribute_Int64Value)(nil),
		(*Attribute_BoolValue)(nil),
		(*Attribute_DoubleValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_events_proto_rawDesc), len(file_events_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_events_proto_goTypes,
		DependencyIndexes: file_events_proto_depIdxs,
		MessageInfos:      file_events_proto_msgTypes,
	}.Build()
	File_events_proto = out.File
	file_events_proto_goTypes = nil
	file_events_proto_depIdxs = nil
}
